sonar.projectKey=printguard
sonar.projectName=PrintGuard
sonar.projectVersion=0.9.0
sonar.sources=src,apps,include
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.scm.disabled=true

# C++ properties for sonar-cxx plugin
sonar.cxx.file.suffixes=.cpp,.hpp,.h
sonar.cxx.std=c++20
sonar.cxx.compilationDatabase=build_sonar/compile_commands.json
sonar.cxx.includeDirectories=/usr/src/include,/usr/src/build_sonar/_deps/spdlog-src/include,/usr/src/build_sonar/_deps/libpqxx-src/include,/usr/src/build_sonar/_deps/libpqxx-build/include,/usr/src/build_sonar/_deps/httplib-src,/usr/src/build_sonar/_deps/catch2-src/src,/usr/src/build_sonar/_deps/catch2-build/generated-includes,/usr/include/c++/13,/usr/include/x86_64-linux-gnu/c++/13,/usr/include/c++/13/backward,/usr/lib/gcc/x86_64-linux-gnu/13/include,/usr/local/include,/usr/include/x86_64-linux-gnu,/usr/include,/usr/include/qpdf,/usr/include/openssl,/usr/include/linux,/usr/include/asm-generic
sonar.cxx.errorRecoveryEnabled=true
sonar.cxx.defines=__x86_64__=1,__linux__=1,__GNUC__=13,__cplusplus=202002L,SPDLOG_COMPILED_LIB=1,__LP64__=1
sonar.coverageReportPaths=build_sonar/coverage.xml

sonar.inclusions=**/*.cpp,**/*.hpp,**/*.h
sonar.exclusions=build/**,third_party/**,tools/**
